version: '3'

services:
  agro_db:
    image: postgres
    container_name: agro_bonsai
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=agro_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=AGRO_DATABASE
    volumes:
      - ./postgres:/var/lib/postgresql/data
